name: barberia_ui
description: A flutter design system for mobile platforms used internally in Barberia applications.
version: 0.10.2

publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: OpenSans
      fonts:
        - asset: packages/barberia_ui/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: packages/barberia_ui/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: packages/barberia_ui/fonts/OpenSans-Bold.ttf
          weight: 700
